### ISSUE TITLE
Angular UI 1.4.3 compatibility

### ISSUE THREAD

**Issue by conveys** [themyth92/ng-bootstrap-lightbox#1]
Hello @themyth92 very good script and very handy, any plans to support Angular UI 1.4.3?

**Comment by themyth92** [comment]
I still dont have any plans for joining Angular UI at the moment. I think it is quite simple and still need some improvements to make it better though.

**Comment by conveys** [comment]
Makes totally sense, @themyth92 please email at luis@creativestud.io, wondering if you are available to help with some development work.

**Comment by themyth92** [comment]
Hi, I am currently busy with my work at the moment so I am not available with some other development work. Sorry about that :)
